### ISSUE TITLE
Interface (Kimberly)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#9]
Kimberly:"Okay I am going to take the interface for my part. It is supposed a fun and easily usable interface without any confusions. "

**Comment by kimberly-moors** [comment]
Hey Helke,
I did a new merge. The bar charts are still going to undergo some changes (maybe even change into a histogram).
All the other buttons are supposed to work.
As for the simplify button. For the moment I added the sentence splitter which you can find in the function_lib which is supposed to become a part of the sentence simplification

**Comment by kimberly-moors** [comment]
I am done with the interface. When you are done with your parts can you put them on Github. I have to implement them in my interface.

As for the layout. Since I didn't hear anything I'll suppose everything is alright? I'll consider the layout fixed since time is shortening and I don't have time left to change everything.
